version: '3.6'

volumes:
  animedb:
    driver: local

services:
  animedb:
    image: postgres
    environment:
      POSTGRES_USER: anime_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: animedb
      TZ: GMT-3
    volumes:
      - animedb:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nats:
    image: nats
    ports:
      - 4222:4222