-- +migrate Up
CREATE TABLE ANIMES (
    ID SERIAL PRIMARY KEY,
    EXTERNALID VARCHAR(255) NOT NULL,
    RUSNAME VARCHAR(255) NOT NULL,
    ENGNAME VARCHAR(255) NOT NULL,
    IMAGEURL VARCHAR(1024) NOT NULL,
    NEXT_EPISODE_AT TIMESTAMPTZ NOT NULL,
    NOTIFICATION_SENT BOOLEAN NOT NULL
);
CREATE TABLE TELEGRAM_USERS (
    ID SERIAL PRIMARY KEY,
    TELEGRAM_USER_ID VARCHAR(255) NOT NULL,
    TELEGRAM_USERNAME VARCHAR(255) NOT NULL
);
CREATE TABLE SUBSCRIPTIONS (
    TELEGRAM_USER_ID BIGINT REFERENCES TELEGRAM_USERS(ID),
    ANIME_ID BIGINT REFERENCES ANIMES(ID) ON DELETE CASCADE,
    PRIMARY KEY(TELEGRAM_USER_ID, ANIME_ID)
);
-- +migrate Down